module.exports = {
	".css": "text/css",
	".gif": "image/gif",
	".html": "text/html",
	".ico": "image/x-icon",
	".jpeg": "image/jpeg",
	".jpg": "image/jpeg",
	".js": "text/javascript",
	".json": "application/json",
	".pdf": "application/pdf",
	".png": "image/png",
	".svg": "image/svg+xml",
	".tiff": "image/tiff",
	".txt": "text/plain",
	".xml": "text/xml",
	".md": "text/plain",
	".webm": "video/webm",
	".mp4": "video/mpeg",
	".mp3": "audio/mpeg"
}